language: node_js

node_js:
  - '10'

cache: npm

git:
  depth: 3

jobs:
  include:
    - stage: lint
      name: Lint code
      script:
        - npm run lint
        - commitlint-travis

    - stage: changelog
      if: branch = master
      name: Generate changelog
      script:
        - npm run changelog

    - stage: release
      if: branch = master
      name: Release
      script:
        - npm run semantic-release

    - stage: deploy
      if: branch = master
      name: Storybook deploy
      script:
        npm run deploy:github -- --ci


