language: node_js

node_js:
  - '10'

git:
  depth: 3

branches:
  only:
  - master

stages:
  - name: release
    if: branch = develop
  - name: deploy
    if: branch = develop

jobs:
  include:
    - stage: lint
      name: Lint code
      script:
        - npm run lint
        - commitlint-travis

    - stage: changelog
      name: Generate changelog
      script:
        - npm run changelog

    - stage: release
      name: Release
      script:
        - npm run semantic-release

    - stage: deploy
      name: Storybook deploy
      script:
        npm run deploy:github -- --ci


