language: node_js

node_js:
  - '10'

stages:
  - name: release
    if: branch = develop
  - name: deploy
    if: branch = develop

jobs:
  include:
    - stage: lint
      name: Lint
      script:
        - npm run lint
        - commitlint-travis

    - stage: release
      name: Release
      # deploy:
      #   provider: script
      #   skip_cleanup: true
      script:
        - npm run semantic-release

    - stage: changelog
      name: Generate changelog
      script:
        - npm run changelog

    - stage: deploy
      name: Storybook deploy
      script:
        npm run deploy:github -- --ci


